version: 0.2

phases:

  install:
    runtime-versions:
      dotnet: 6.0

  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release -o publish

  post_build:
    commands:
      - echo "Preparing CodeDeploy bundle"
      - cp appspec.yml publish/
      - cp -r scripts publish/

artifacts:
  base-directory: publish
  files:
    - '**/*'
